services:
  frontend:
    container_name: crypto_dashboard_frontend
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - my_shared_network
    environment:
      - VITE_TELEGRAM_BOT_URL=${VITE_TELEGRAM_BOT_URL}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_BINANCE_API=${VITE_BINANCE_API}

networks:
  my_shared_network:
    external: true