name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            
            export VITE_TELEGRAM_BOT_URL: ${{ secrets.VITE_TELEGRAM_BOT_URL }}
            export VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
            export VITE_BINANCE_API: ${{ secrets.VITE_BINANCE_API }}
            
            if [ ! -d "/root/crypto-dashboard-frontend" ]; then
              git clone --depth=1 -b master https://github.com/saygoodluck/crypto-dashboard-frontend.git /root/crypto-dashboard-frontend
              cd /root/crypto-dashboard-frontend
            else
              cd /root/crypto-dashboard-frontend
              git pull
            fi
            
            docker compose -f docker-compose.yaml stop
            docker compose -f docker-compose.yaml rm -f
            docker compose -f docker-compose.yaml up -d --build